[profile.default]
solc = "0.8.30"
src = "src"
out = "out"
libs = ["lib"]
evm_version = "shanghai"
optimizer = true
optimizer_runs = 0
bytecode_hash = "none"
cbor_metadata = false
always_use_create_2_factory = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
